package com.reza.reducer.processor

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate
import com.reza.reducer.annotations.GenerateUpdaters
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.writeTo
import com.squareup.kotlinpoet.ksp.toTypeName

class StateReducerProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotationName = GenerateUpdaters::class.qualifiedName
            ?: "com.reza.reducer.annotations.GenerateUpdaters"

        val symbols = resolver.getSymbolsWithAnnotation(annotationName)
        val unableToProcess = symbols.filterNot { it.validate() }.toList()

        symbols
            .filter { it is KSClassDeclaration && it.validate() }
            .map { it as KSClassDeclaration }
            .forEach { classDeclaration ->
                // Ensure it's actually a data class
                if (!classDeclaration.modifiers.contains(Modifier.DATA)) {
                    logger.error("@GenerateUpdaters can only be applied to data classes", classDeclaration)
                    return@forEach
                }
                generateUpdatersForClass(classDeclaration)
            }

        return unableToProcess
    }

    private fun generateUpdatersForClass(classDeclaration: KSClassDeclaration) {
        val packageName = classDeclaration.packageName.asString()
        val className = classDeclaration.simpleName.asString()
        val classType = classDeclaration.toClassName()

        // File building setup via KotlinPoet
        val fileBuilder = FileSpec.builder(packageName, "${className}Updaters")
            .addFileComment(
                """
                ========================================================================
                AUTO-GENERATED FILE. DO NOT MODIFY.
                This file was generated by StateReducer (KSP).
                Any manual changes made to this file will be overwritten upon next build.
                ========================================================================
                """.trimIndent()
            )

        val properties = classDeclaration.getAllProperties()
        for (property in properties) {
            val propertyName = property.simpleName.asString()
            val resolvedType = property.type.resolve()
            val propertyTypeName = resolvedType.toTypeName()
            val capitalizedName = propertyName.replaceFirstChar { it.uppercase() }

            // Check if the property is another data class (complex type)
            val isDataClass = (resolvedType.declaration as? KSClassDeclaration)
                ?.modifiers?.contains(Modifier.DATA) == true

            // Direct Value
            val directValueFunction = FunSpec.builder("update$capitalizedName")
                .receiver(classType)
                .returns(classType)
                .addParameter("value", propertyTypeName)
                .addStatement("return this.copy(%L = value)", propertyName)
                .build()

            // Transformer Lambda:
            // - For nested Data Classes: (DSL Scope)
            // - For Primitives/Other Types: (Standard Scope)
            val transformFunction = if (isDataClass) {
                val dslLambdaParam = LambdaTypeName.get(
                    receiver = propertyTypeName,
                    returnType = propertyTypeName
                )
                FunSpec.builder("update$capitalizedName")
                    .receiver(classType)
                    .returns(classType)
                    .addParameter("block", dslLambdaParam)
                    .addStatement("return this.copy(%L = this.%L.block())", propertyName, propertyName)
                    .build()
            } else {
                val standardLambdaParam = LambdaTypeName.get(
                    parameters = arrayOf(propertyTypeName),
                    returnType = propertyTypeName
                )
                FunSpec.builder("update$capitalizedName")
                    .receiver(classType)
                    .returns(classType)
                    .addParameter("transform", standardLambdaParam)
                    .addStatement("return this.copy(%L = transform(this.%L))", propertyName, propertyName)
                    .build()
            }

            fileBuilder.addFunction(directValueFunction)
            fileBuilder.addFunction(transformFunction)
        }

        fileBuilder.build().writeTo(codeGenerator = codeGenerator, aggregating = false)
    }
}